config/routes.rb
MonkeyBarrel::Application.routes.draw do
  root to: 'application#index'

  resources :users do
    member do
      post 'add_tag'
      post 'remove_tag'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :username
  acts_as_taggable

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def tags
    self.tag_list.to_a
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path, :notice => "New user created successfully"
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to users_path, :notice => "User has been updated"
    else
      redirect_to users_path, :alert => "Error up dating user information"
    end
  end

  def destroy
    @user = User.find(params[:id])
    if User.destroy(params[:id])
      redirect_to users_path, :notice => 'User has been deleted'
    end
  end

  def user_params
    params.require(:user).permit(:name, :tag_list) ## Rails 4 strong params usage
  end

  def add_tag
    @user = User.find(params[:id])
    @user.tag_list.add(params[:tag])
    if @user.save
      redirect_to users_path, :notice => "Tags have been updated successfully"
    else
      redirect_to users_path, :alert => "Error updating tags"
    end
  end

  def remove_tag
    @user = User.find(params[:id])
    @user.tag_list.remove(params[:tag])
    if @user.save
      redirect_to users_path, :notice => "Tags have been updated successfully"
    else
      redirect_to users_path, :alert => "Error updating tags"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<h1>Hello Monkeys</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MonkeyBarrel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
        <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to "Users", users_path %></li>
      </ul>
  </div>
</div>
<br />
<div class="container">
  <div class="page-header">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}", :class => 'alert alert-success'%>
      <% end %>
    </div>
  <%= yield %>
</div>
</body>
</html>

app/views/users/_form.html.erb
<div class="well well-lg">
 <%= form_for @user, :html => {:class => "form-horizontal"} do |f|  %>
    <fieldset>
      <legend class="text-center header">New User Info</legend>
        <div class="form-group">
          <span class="col-md-2">Username:</span>
          <div class="col-md-8"><%= f.text_field :username, :placeholder => 'username', :class=> 'form-control' %></div>
        </div>
        <div class="form-group">
          <span class="col-md-2">First Name:</span>
          <div class="col-md-8"><%= f.text_field :first_name, :placeholder => 'First Name', :class=> 'form-control' %></div>
        </div>
        <div class="form-group">
          <span class="col-md-2">Last Name:</span>
          <div class="col-md-8"><%= f.text_field :last_name, :placeholder => 'Last Name', :class=> 'form-control' %></div>
        </div>
        <div class="form-group">
          <div class="col-md-10 text-center">
            <%= f.submit :class => "btn btn-sm btn-primary"%> <%= link_to 'Cancel', users_path, :class => "btn btn-sm btn-primary" %>
          </div>
        </div>
    </fieldset>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render :partial => "form" %>

app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to 'Add User', new_user_path, :class => 'btn btn-sm btn-primary' %>
<br />
<br />
<div class="well well-lg">
    <ul class="list-group">
    <% @users.each do |user| %>
        <li class="list-group-item">
          <span class="col-md-4"><%= link_to user.full_name, user_path(user.id)%></span>
          <%= link_to 'Edit', edit_user_path(user.id), :class => 'btn btn-sm btn-info' %>
          <%= link_to 'Delete', user, :method => 'delete', :class => 'btn btn-sm btn-danger', :style => 'display: inline-block;' %>
          <br />
          <% user.tags.each do |tag| %>
            <span class="label label-info"><%= tag %></span>
          <% end %>
        </li>
    <% end %>
    </ul>
</div>

app/views/users/new.html.erb
<h1>Add user</h1>

<%= render :partial => "form" %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>

<div class="form-group">
    <%= form_tag add_tag_user_path, method: :post do %>
        <div class="col-md-4"><%= text_field_tag :tag, nil, placeholder: 'New Tag', class: 'form-control' %></div>
        <%= submit_tag 'Add Tag', class: 'btn btn-sm btn-primary' %>
    <% end %>
</div>